Add WhatsApp to NativeApp
Plant-for-the-Planet-org/FireAlert pull request #157
Opened 2024-02-22 11:12 UTC by dhakalaashish

This PR adds WhatsApp to nativeapp and updates the server implementation as well.

2024-02-26 12:50 UTC, mohitb35 commented on apps/nativeapp/app/components/phoneInput/PhoneInput.tsx
> +import {EXCLUDED_COUNTRIES, EXCLUDED_COUNTRIES_WHATSAPP} from '../../constants';
I'd suggest renaming EXCLUDED_COUNTRIES to indicate it includes countries where SMS is disabled.

2024-02-27 05:14 UTC, mohitb35 commented on apps/server/src/server/api/routers/alertMethod.ts
> +                const isDestinationAccepted = !isPhoneNumberRestricted('whatsapp', input.destination);
Is this check not needed for `verify:`?

2024-02-27 05:17 UTC, mohitb35 commented on apps/nativeapp/app/screens/Verification/Verification.tsx
> +      );
There's a double check for `verificationType === 'Sms` here - that can be removed

2024-02-27 05:18 UTC, mohitb35 commented on apps/nativeapp/app/screens/Settings/Settings.tsx
> +  };
Needs to be commented

2024-02-27 05:23 UTC, mohitb35 commented on apps/nativeapp/app/screens/Login/Login.tsx
> +        {ephemeralSession: false, useLegacyCallbackUrl: true},
Is this an intermediate step? What stops us from updating the Auth0 callback Url, or adding a new one?

2024-02-27 05:24 UTC, mohitb35 requested changes
@dhakalaashish I've requested some minor changes. And raised some points of clarification.

2024-02-27 09:24 UTC, dhakalaashish commented on apps/server/src/server/api/routers/alertMethod.ts
> +                const isDestinationAccepted = !isPhoneNumberRestricted('whatsapp', input.destination);
We are dynamically restricting phone numbers conditionally. Only Indian numbers are restricted for WhatsApp, while sms are restricted for about 8 countries.

2024-02-27 09:26 UTC, dhakalaashish commented on apps/nativeapp/app/screens/Login/Login.tsx
> +        {ephemeralSession: false, useLegacyCallbackUrl: true},
This Boolean is necessary to ensure conflict-free migration from react-native-auth0 from v2 to v3.

2024-02-27 09:26 UTC, dhakalaashish commented on apps/nativeapp/app/screens/Settings/Settings.tsx
> +  };
Done. Thank you.

2024-02-27 09:27 UTC, dhakalaashish commented on apps/nativeapp/app/screens/Verification/Verification.tsx
> +      );
Done. Thank you.

2024-02-27 09:41 UTC, dhakalaashish commented
@mohitb35 Thank you for your feedback. I've made most of the suggested changes, but retained some for correctness.

2024-02-27 09:53 UTC, mohitb35 approved these changes
LGTM once conflicts are resolved

2024-02-27 11:40 UTC, merged